steps:
# This step install npm packages
- name: 'gcr.io/cloud-builders/npm'
  id: Install
  args: ['install']

# This step runs the unit tests on the app
- name: 'gcr.io/cloud-builders/npm'
  id: Test
  args: ['test']

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/cirrus-initial-project/demo-cicd:latest'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/cirrus-initial-project/demo-cicd:latest'
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'kubernetes.yml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=istio-cluster'
- name: 'gcr.io/cloud-builders/kubectl'
  id: Fetch changes
  args:
  - 'rollout'
  - 'restart'
  - 'deployment/demo-cicd'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=istio-cluster'
